import { Chip } from "@nextui-org/react";
import { Icon } from "@iconify/react";

import { SidebarItemType } from "./SidebarBox";

export const sectionItems = [
    {
        key: "overview",
        title: "Overview",
        items: [
            {
                key: "dashboard",
                href: "/dashboard",
                icon: "solar:home-2-linear",
                title: "Tableau de bord",
                // requiredFeature: "feature_suppliers",
                // requiredPermission: "view_suppliers",
            },
            {
                key: "reports",
                href: "/dashboard/reports",
                icon: "icon-park-outline:sales-report",
                title: "Rapports",
                requiredPermission: "reports_view",
                requiredFeature: "feature_reports",
                endContent: (
                    <Chip startContent={<Icon icon={"hugeicons:ai-idea"} width={12} />} color="warning" className="bg-emerald-500 text-white" size="sm" variant="flat">
                        IA
                    </Chip>
                ),
            },
            {
                key: "stocks",
                title: "Paramètrage",
                icon: "lsicon:management-stockout-outline",
                type: SidebarItemType.Nest,
                requiredFeature: "feature_inventory",
                requiredPermission: "inventory_view",
                items: [
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                ],
            },
            {
                key: "stocks",
                title: "Paramètrage",
                icon: "lsicon:management-stockout-outline",
                type: SidebarItemType.Nest,
                requiredFeature: "feature_inventory",
                requiredPermission: "inventory_view",
                items: [
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                    {
                        key: "stock_management",
                        icon: "tabler:building-warehouse",
                        href: "dashboard/settings/directions",
                        title: "Directions",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_view",
                    },
                    {
                        key: "stock_transfer",
                        icon: "hugeicons:folder-transfer",
                        href: "/dashboard/settings/postes",
                        title: "Postes",
                        requiredFeature: "feature_inventory",
                        requiredPermission: "inventory_transfer",
                    },
                ],
            },
        ],
    },
];
