const countries = [
    { id: "1", code: "AF", name_en: "Afghanistan", name: "Afghanistan", code_tel: "93" },
    { id: "2", code: "AX", name_en: "Aland Islands", name: "Îles Åland", code_tel: "358" },
    { id: "3", code: "AL", name_en: "Albania", name: "Albanie", code_tel: "355" },
    { id: "4", code: "DZ", name_en: "Algeria", name: "Algérie", code_tel: "213" },
    { id: "5", code: "AS", name_en: "American Samoa", name: "Samoa américaines", code_tel: "1+684" },
    { id: "6", code: "AD", name_en: "Andorra", name: "Andorre", code_tel: "376" },
    { id: "7", code: "AO", name_en: "Angola", name: "Angola", code_tel: "244" },
    { id: "8", code: "AI", name_en: "Anguilla", name: "Anguilla", code_tel: "1+264" },
    { id: "9", code: "AQ", name_en: "Antarctica", name: "Antarctique", code_tel: "672" },
    { id: "10", code: "AG", name_en: "Antigua and Barbuda", name: "Antigua-et-Barbuda", code_tel: "1+268" },
    { id: "11", code: "AR", name_en: "Argentina", name: "Argentine", code_tel: "54" },
    { id: "12", code: "AM", name_en: "Armenia", name: "Arménie", code_tel: "374" },
    { id: "13", code: "AW", name_en: "Aruba", name: "Aruba", code_tel: "297" },
    { id: "14", code: "AU", name_en: "Australia", name: "Australie", code_tel: "61" },
    { id: "15", code: "AT", name_en: "Austria", name: "Autriche", code_tel: "43" },
    { id: "16", code: "AZ", name_en: "Azerbaijan", name: "Azerbaïdjan", code_tel: "994" },
    { id: "17", code: "BS", name_en: "Bahamas", name: "Bahamas", code_tel: "1+242" },
    { id: "18", code: "BH", name_en: "Bahrain", name: "Bahreïn", code_tel: "973" },
    { id: "19", code: "BD", name_en: "Bangladesh", name: "Bangladesh", code_tel: "880" },
    { id: "20", code: "BB", name_en: "Barbados", name: "Barbade", code_tel: "1+246" },
    { id: "21", code: "BY", name_en: "Belarus", name: "Biélorussie", code_tel: "375" },
    { id: "22", code: "BE", name_en: "Belgium", name: "Belgique", code_tel: "32" },
    { id: "23", code: "BZ", name_en: "Belize", name: "Belize", code_tel: "501" },
    { id: "24", code: "BJ", name_en: "Benin", name: "Bénin", code_tel: "229" },
    { id: "25", code: "BM", name_en: "Bermuda", name: "Bermudes", code_tel: "1+441" },
    { id: "26", code: "BT", name_en: "Bhutan", name: "Bhoutan", code_tel: "975" },
    { id: "27", code: "BO", name_en: "Bolivia", name: "Bolivie", code_tel: "591" },
    { id: "28", code: "BQ", name_en: "Bonaire, Sint Eustatius and Saba", name: "Bonaire, Saint-Eustache et Saba", code_tel: "599" },
    { id: "29", code: "BA", name_en: "Bosnia and Herzegovina", name: "Bosnie-Herzégovine", code_tel: "387" },
    { id: "30", code: "BW", name_en: "Botswana", name: "Botswana", code_tel: "267" },
    { id: "31", code: "BV", name_en: "Bouvet Island", name: "Île Bouvet", code_tel: "NONE" },
    { id: "32", code: "BR", name_en: "Brazil", name: "Brésil", code_tel: "55" },
    { id: "33", code: "IO", name_en: "British Indian Ocean Territory", name: "Territoire britannique de l’océan Indien", code_tel: "246" },
    { id: "34", code: "BN", name_en: "Brunei", name: "Brunéi", code_tel: "673" },
    { id: "35", code: "BG", name_en: "Bulgaria", name: "Bulgarie", code_tel: "359" },
    { id: "36", code: "BF", name_en: "Burkina Faso", name: "Burkina Faso", code_tel: "226" },
    { id: "37", code: "BI", name_en: "Burundi", name: "Burundi", code_tel: "257" },
    { id: "38", code: "KH", name_en: "Cambodia", name: "Cambodge", code_tel: "855" },
    { id: "39", code: "CM", name_en: "Cameroon", name: "Cameroun", code_tel: "237" },
    { id: "40", code: "CA", name_en: "Canada", name: "Canada", code_tel: "1" },
    { id: "41", code: "CV", name_en: "Cape Verde", name: "Cap-Vert", code_tel: "238" },
    { id: "42", code: "KY", name_en: "Cayman Islands", name: "Îles Caïmans", code_tel: "1+345" },
    { id: "43", code: "CF", name_en: "Central African Republic", name: "République centrafricaine", code_tel: "236" },
    { id: "44", code: "TD", name_en: "Chad", name: "Tchad", code_tel: "235" },
    { id: "45", code: "CL", name_en: "Chile", name: "Chili", code_tel: "56" },
    { id: "46", code: "CN", name_en: "China", name: "Chine", code_tel: "86" },
    { id: "47", code: "CX", name_en: "Christmas Island", name: "Île Christmas", code_tel: "61" },
    { id: "48", code: "CC", name_en: "Cocos (Keeling) Islands", name: "Îles Cocos", code_tel: "61" },
    { id: "49", code: "CO", name_en: "Colombia", name: "Colombie", code_tel: "57" },
    { id: "50", code: "KM", name_en: "Comoros", name: "Comores", code_tel: "269" },
    { id: "51", code: "CG", name_en: "Congo", name: "Congo", code_tel: "242" },
    { id: "52", code: "CK", name_en: "Cook Islands", name: "Îles Cook", code_tel: "682" },
    { id: "53", code: "CR", name_en: "Costa Rica", name: "Costa Rica", code_tel: "506" },
    { id: "54", code: "CI", name_en: "Cote d'ivoire (Ivory Coast)", name: "Côte d’Ivoire", code_tel: "225" },
    { id: "55", code: "HR", name_en: "Croatia", name: "Croatie", code_tel: "385" },
    { id: "56", code: "CU", name_en: "Cuba", name: "Cuba", code_tel: "53" },
    { id: "57", code: "CW", name_en: "Curacao", name: "Curaçao", code_tel: "599" },
    { id: "58", code: "CY", name_en: "Cyprus", name: "Chypre", code_tel: "357" },
    { id: "59", code: "CZ", name_en: "Czech Republic", name: "République tchèque", code_tel: "420" },
    { id: "60", code: "CD", name_en: "Democratic Republic of the Congo", name: "République démocratique du Congo", code_tel: "243" },
    { id: "61", code: "DK", name_en: "Denmark", name: "Danemark", code_tel: "45" },
    { id: "62", code: "DJ", name_en: "Djibouti", name: "Djibouti", code_tel: "253" },
    { id: "63", code: "DM", name_en: "Dominica", name: "Dominique", code_tel: "1+767" },
    { id: "64", code: "DO", name_en: "Dominican Republic", name: "République dominicaine", code_tel: "1+809, 8" },
    { id: "65", code: "EC", name_en: "Ecuador", name: "Équateur", code_tel: "593" },
    { id: "66", code: "EG", name_en: "Egypt", name: "Égypte", code_tel: "20" },
    { id: "67", code: "SV", name_en: "El Salvador", name: "Salvador", code_tel: "503" },
    { id: "68", code: "GQ", name_en: "Equatorial Guinea", name: "Guinée équatoriale", code_tel: "240" },
    { id: "69", code: "ER", name_en: "Eritrea", name: "Érythrée", code_tel: "291" },
    { id: "70", code: "EE", name_en: "Estonia", name: "Estonie", code_tel: "372" },
    { id: "71", code: "ET", name_en: "Ethiopia", name: "Éthiopie", code_tel: "251" },
    { id: "72", code: "FK", name_en: "Falkland Islands (Malvinas)", name: "Îles Falkland (Malvinas)", code_tel: "500" },
    { id: "73", code: "FO", name_en: "Faroe Islands", name: "Îles Féroé", code_tel: "298" },
    { id: "74", code: "FJ", name_en: "Fiji", name: "Fidji", code_tel: "679" },
    { id: "75", code: "FI", name_en: "Finland", name: "Finlande", code_tel: "358" },
    { id: "76", code: "FR", name_en: "France", name: "France", code_tel: "33" },
    { id: "77", code: "GF", name_en: "French Guiana", name: "Guyane française", code_tel: "594" },
    { id: "78", code: "PF", name_en: "French Polynesia", name: "Polynésie française", code_tel: "689" },
    { id: "79", code: "TF", name_en: "French Southern Territories", name: "Terres australes françaises", code_tel: null },
    { id: "80", code: "GA", name_en: "Gabon", name: "Gabon", code_tel: "241" },
    { id: "81", code: "GM", name_en: "Gambia", name: "Gambie", code_tel: "220" },
    { id: "82", code: "GE", name_en: "Georgia", name: "Géorgie", code_tel: "995" },
    { id: "83", code: "DE", name_en: "Germany", name: "Allemagne", code_tel: "49" },
    { id: "84", code: "GH", name_en: "Ghana", name: "Ghana", code_tel: "233" },
    { id: "85", code: "GI", name_en: "Gibraltar", name: "Gibraltar", code_tel: "350" },
    { id: "86", code: "GR", name_en: "Greece", name: "Grèce", code_tel: "30" },
    { id: "87", code: "GL", name_en: "Greenland", name: "Groenland", code_tel: "299" },
    { id: "88", code: "GD", name_en: "Grenada", name: "Grenade", code_tel: "1+473" },
    { id: "89", code: "GP", name_en: "Guadaloupe", name: "Guadeloupe", code_tel: "590" },
    { id: "90", code: "GU", name_en: "Guam", name: "Guam", code_tel: "1+671" },
    { id: "91", code: "GT", name_en: "Guatemala", name: "Guatemala", code_tel: "502" },
    { id: "92", code: "GG", name_en: "Guernsey", name: "Guernesey", code_tel: "44" },
    { id: "93", code: "GN", name_en: "Guinea", name: "Guinée", code_tel: "224" },
    { id: "94", code: "GW", name_en: "Guinea-Bissau", name: "Guinée-Bissau", code_tel: "245" },
    { id: "95", code: "GY", name_en: "Guyana", name: "Guyana", code_tel: "592" },
    { id: "96", code: "HT", name_en: "Haiti", name: "Haïti", code_tel: "509" },
    { id: "97", code: "HM", name_en: "Heard Island and McDonald Islands", name: "Îles Heard-et-MacDonald", code_tel: "NONE" },
    { id: "98", code: "HN", name_en: "Honduras", name: "Honduras", code_tel: "504" },
    { id: "99", code: "HK", name_en: "Hong Kong", name: "Hong Kong", code_tel: "852" },
    { id: "100", code: "HU", name_en: "Hungary", name: "Hongrie", code_tel: "36" },
    { id: "101", code: "IS", name_en: "Iceland", name: "Islande", code_tel: "354" },
    { id: "102", code: "IN", name_en: "India", name: "Inde", code_tel: "91" },
    { id: "103", code: "ID", name_en: "Indonesia", name: "Indonésie", code_tel: "62" },
    { id: "104", code: "IR", name_en: "Iran", name: "Iran", code_tel: "98" },
    { id: "105", code: "IQ", name_en: "Iraq", name: "Irak", code_tel: "964" },
    { id: "106", code: "IE", name_en: "Ireland", name: "Irlande", code_tel: "353" },
    { id: "107", code: "IM", name_en: "Isle of Man", name: "Île de Man", code_tel: "44" },
    { id: "108", code: "IL", name_en: "Israel", name: "Israël", code_tel: "972" },
    { id: "109", code: "IT", name_en: "Italy", name: "Italie", code_tel: "39" },
    { id: "110", code: "JM", name_en: "Jamaica", name: "Jamaïque", code_tel: "1+876" },
    { id: "111", code: "JP", name_en: "Japan", name: "Japon", code_tel: "81" },
    { id: "112", code: "JE", name_en: "Jersey", name: "Jersey", code_tel: "44" },
    { id: "113", code: "JO", name_en: "Jordan", name: "Jordanie", code_tel: "962" },
    { id: "114", code: "KZ", name_en: "Kazakhstan", name: "Kazakhstan", code_tel: "7" },
    { id: "115", code: "KE", name_en: "Kenya", name: "Kenya", code_tel: "254" },
    { id: "116", code: "KI", name_en: "Kiribati", name: "Kiribati", code_tel: "686" },
    { id: "117", code: "XK", name_en: "Kosovo", name: "Kosovo", code_tel: "381" },
    { id: "118", code: "KW", name_en: "Kuwait", name: "Koweït", code_tel: "965" },
    { id: "119", code: "KG", name_en: "Kyrgyzstan", name: "Kirghizistan", code_tel: "996" },
    { id: "120", code: "LA", name_en: "Laos", name: "Laos", code_tel: "856" },
    { id: "121", code: "LV", name_en: "Latvia", name: "Lettonie", code_tel: "371" },
    { id: "122", code: "LB", name_en: "Lebanon", name: "Liban", code_tel: "961" },
    { id: "123", code: "LS", name_en: "Lesotho", name: "Lesotho", code_tel: "266" },
    { id: "124", code: "LR", name_en: "Liberia", name: "Liberia", code_tel: "231" },
    { id: "125", code: "LY", name_en: "Libya", name: "Libye", code_tel: "218" },
    { id: "126", code: "LI", name_en: "Liechtenstein", name: "Liechtenstein", code_tel: "423" },
    { id: "127", code: "LT", name_en: "Lithuania", name: "Lituanie", code_tel: "370" },
    { id: "128", code: "LU", name_en: "Luxembourg", name: "Luxembourg", code_tel: "352" },
    { id: "129", code: "MO", name_en: "Macao", name: "Macao", code_tel: "853" },
    { id: "130", code: "MK", name_en: "Macedonia", name: "Macédoine", code_tel: "389" },
    { id: "131", code: "MG", name_en: "Madagascar", name: "Madagascar", code_tel: "261" },
    { id: "132", code: "MW", name_en: "Malawi", name: "Malawi", code_tel: "265" },
    { id: "133", code: "MY", name_en: "Malaysia", name: "Malaisie", code_tel: "60" },
    { id: "134", code: "MV", name_en: "Maldives", name: "Maldives", code_tel: "960" },
    { id: "135", code: "ML", name_en: "Mali", name: "Mali", code_tel: "223" },
    { id: "136", code: "MT", name_en: "Malta", name: "Malte", code_tel: "356" },
    { id: "137", code: "MH", name_en: "Marshall Islands", name: "Îles Marshall", code_tel: "692" },
    { id: "138", code: "MQ", name_en: "Martinique", name: "Martinique", code_tel: "596" },
    { id: "139", code: "MR", name_en: "Mauritania", name: "Mauritanie", code_tel: "222" },
    { id: "140", code: "MU", name_en: "Mauritius", name: "Maurice", code_tel: "230" },
    { id: "141", code: "YT", name_en: "Mayotte", name: "Mayotte", code_tel: "262" },
    { id: "142", code: "MX", name_en: "Mexico", name: "Mexique", code_tel: "52" },
    { id: "143", code: "FM", name_en: "Micronesia", name: "Micronésie", code_tel: "691" },
    { id: "144", code: "MD", name_en: "Moldava", name: "Moldavie", code_tel: "373" },
    { id: "145", code: "MC", name_en: "Monaco", name: "Monaco", code_tel: "377" },
    { id: "146", code: "MN", name_en: "Mongolia", name: "Mongolie", code_tel: "976" },
    { id: "147", code: "ME", name_en: "Montenegro", name: "Monténégro", code_tel: "382" },
    { id: "148", code: "MS", name_en: "Montserrat", name: "Montserrat", code_tel: "1+664" },
    { id: "149", code: "MA", name_en: "Morocco", name: "Maroc", code_tel: "212" },
    { id: "150", code: "MZ", name_en: "Mozambique", name: "Mozambique", code_tel: "258" },
    { id: "151", code: "MM", name_en: "Myanmar (Burma)", name: "Myanmar (Birmanie)", code_tel: "95" },
    { id: "152", code: "NA", name_en: "Namibia", name: "Namibie", code_tel: "264" },
    { id: "153", code: "NR", name_en: "Nauru", name: "Nauru", code_tel: "674" },
    { id: "154", code: "NP", name_en: "Nepal", name: "Népal", code_tel: "977" },
    { id: "155", code: "NL", name_en: "Netherlands", name: "Pays-Bas", code_tel: "31" },
    { id: "156", code: "NC", name_en: "New Caledonia", name: "Nouvelle-Calédonie", code_tel: "687" },
    { id: "157", code: "NZ", name_en: "New Zealand", name: "Nouvelle-Zélande", code_tel: "64" },
    { id: "158", code: "NI", name_en: "Nicaragua", name: "Nicaragua", code_tel: "505" },
    { id: "159", code: "NE", name_en: "Niger", name: "Niger", code_tel: "227" },
    { id: "160", code: "NG", name_en: "Nigeria", name: "Nigeria", code_tel: "234" },
    { id: "161", code: "NU", name_en: "Niue", name: "Niue", code_tel: "683" },
    { id: "162", code: "NF", name_en: "Norfolk Island", name: "Île Norfolk", code_tel: "672" },
    { id: "163", code: "KP", name_en: "North Korea", name: "Corée du Nord", code_tel: "850" },
    { id: "164", code: "MP", name_en: "Northern Mariana Islands", name: "Îles Mariannes du Nord", code_tel: "1+670" },
    { id: "165", code: "NO", name_en: "Norway", name: "Norvège", code_tel: "47" },
    { id: "166", code: "OM", name_en: "Oman", name: "Oman", code_tel: "968" },
    { id: "167", code: "PK", name_en: "Pakistan", name: "Pakistan", code_tel: "92" },
    { id: "168", code: "PW", name_en: "Palau", name: "Palaos", code_tel: "680" },
    { id: "169", code: "PS", name_en: "Palestine", name: "Palestine", code_tel: "970" },
    { id: "170", code: "PA", name_en: "Panama", name: "Panama", code_tel: "507" },
    { id: "171", code: "PG", name_en: "Papua New Guinea", name: "Papouasie-Nouvelle-Guinée", code_tel: "675" },
    { id: "172", code: "PY", name_en: "Paraguay", name: "Paraguay", code_tel: "595" },
    { id: "173", code: "PE", name_en: "Peru", name: "Pérou", code_tel: "51" },
    { id: "174", code: "PH", name_en: "Phillipines", name: "", code_tel: "63" },
    { id: "175", code: "PN", name_en: "Pitcairn", name: "Pitcairn", code_tel: "NONE" },
    { id: "176", code: "PL", name_en: "Poland", name: "Pologne", code_tel: "48" },
    { id: "177", code: "PT", name_en: "Portugal", name: "Portugal", code_tel: "351" },
    { id: "178", code: "PR", name_en: "Puerto Rico", name: "Porto Rico", code_tel: "1+939" },
    { id: "179", code: "QA", name_en: "Qatar", name: "Qatar", code_tel: "974" },
    { id: "180", code: "RE", name_en: "Reunion", name: "Réunion", code_tel: "262" },
    { id: "181", code: "RO", name_en: "Romania", name: "Roumanie", code_tel: "40" },
    { id: "182", code: "RU", name_en: "Russia", name: "Russie", code_tel: "7" },
    { id: "183", code: "RW", name_en: "Rwanda", name: "Rwanda", code_tel: "250" },
    { id: "184", code: "BL", name_en: "Saint Barthelemy", name: "Saint-Barthélemy", code_tel: "590" },
    { id: "185", code: "SH", name_en: "Saint Helena", name: "Sainte-Hélène", code_tel: "290" },
    { id: "186", code: "KN", name_en: "Saint Kitts and Nevis", name: "Saint-Kitts-et-Nevis", code_tel: "1+869" },
    { id: "187", code: "LC", name_en: "Saint Lucia", name: "Sainte-Lucie", code_tel: "1+758" },
    { id: "188", code: "MF", name_en: "Saint Martin", name: "Saint-Martin", code_tel: "590" },
    { id: "189", code: "PM", name_en: "Saint Pierre and Miquelon", name: "Saint-Pierre-et-Miquelon", code_tel: "508" },
    { id: "190", code: "VC", name_en: "Saint Vincent and the Grenadines", name: "Saint-Vincent-et-les-Grenadines", code_tel: "1+784" },
    { id: "191", code: "WS", name_en: "Samoa", name: "Samoa", code_tel: "685" },
    { id: "192", code: "SM", name_en: "San Marino", name: "Saint-Marin", code_tel: "378" },
    { id: "193", code: "ST", name_en: "Sao Tome and Principe", name: "Sao Tomé-et-Principe", code_tel: "239" },
    { id: "194", code: "SA", name_en: "Saudi Arabia", name: "Arabie saoudite", code_tel: "966" },
    { id: "195", code: "SN", name_en: "Senegal", name: "Sénégal", code_tel: "221" },
    { id: "196", code: "RS", name_en: "Serbia", name: "Serbie", code_tel: "381" },
    { id: "197", code: "SC", name_en: "Seychelles", name: "Seychelles", code_tel: "248" },
    { id: "198", code: "SL", name_en: "Sierra Leone", name: "Sierra Leone", code_tel: "232" },
    { id: "199", code: "SG", name_en: "Singapore", name: "Singapour", code_tel: "65" },
    { id: "200", code: "SX", name_en: "Sint Maarten", name: "Saint-Martin (partie néerlandaise)", code_tel: "1+721" },
    { id: "201", code: "SK", name_en: "Slovakia", name: "Slovaquie", code_tel: "421" },
    { id: "202", code: "SI", name_en: "Slovenia", name: "Slovénie", code_tel: "386" },
    { id: "203", code: "SB", name_en: "Solomon Islands", name: "Îles Salomon", code_tel: "677" },
    { id: "204", code: "SO", name_en: "Somalia", name: "Somalie", code_tel: "252" },
    { id: "205", code: "ZA", name_en: "South Africa", name: "Afrique du Sud", code_tel: "27" },
    { id: "206", code: "GS", name_en: "South Georgia and the South Sandwich Islands", name: "Géorgie du Sud-et-les Îles Sandwich du Sud", code_tel: "500" },
    { id: "207", code: "KR", name_en: "South Korea", name: "Corée du Sud", code_tel: "82" },
    { id: "208", code: "SS", name_en: "South Sudan", name: "Soudan du Sud", code_tel: "211" },
    { id: "209", code: "ES", name_en: "Spain", name: "Espagne", code_tel: "34" },
    { id: "210", code: "LK", name_en: "Sri Lanka", name: "Sri Lanka", code_tel: "94" },
    { id: "211", code: "SD", name_en: "Sudan", name: "Soudan", code_tel: "249" },
    { id: "212", code: "SR", name_en: "Suriname", name: "Suriname", code_tel: "597" },
    { id: "213", code: "SJ", name_en: "Svalbard and Jan Mayen", name: "Svalbard et Jan Mayen", code_tel: "47" },
    { id: "214", code: "SZ", name_en: "Swaziland", name: "Eswatini (Swaziland)", code_tel: "268" },
    { id: "215", code: "SE", name_en: "Sweden", name: "Suède", code_tel: "46" },
    { id: "216", code: "CH", name_en: "Switzerland", name: "Suisse", code_tel: "41" },
    { id: "217", code: "SY", name_en: "Syria", name: "Syrie", code_tel: "963" },
    { id: "218", code: "TW", name_en: "Taiwan", name: "Taïwan", code_tel: "886" },
    { id: "219", code: "TJ", name_en: "Tajikistan", name: "Tadjikistan", code_tel: "992" },
    { id: "220", code: "TZ", name_en: "Tanzania", name: "Tanzanie", code_tel: "255" },
    { id: "221", code: "TH", name_en: "Thailand", name: "Thaïlande", code_tel: "66" },
    { id: "222", code: "TL", name_en: "Timor-Leste (East Timor)", name: "Timor oriental", code_tel: "670" },
    { id: "223", code: "TG", name_en: "Togo", name: "Togo", code_tel: "228" },
    { id: "224", code: "TK", name_en: "Tokelau", name: "Tokelau", code_tel: "690" },
    { id: "225", code: "TO", name_en: "Tonga", name: "Tonga", code_tel: "676" },
    { id: "226", code: "TT", name_en: "Trinidad and Tobago", name: "Trinité-et-Tobago", code_tel: "1+868" },
    { id: "227", code: "TN", name_en: "Tunisia", name: "Tunisie", code_tel: "216" },
    { id: "228", code: "TR", name_en: "Turkey", name: "Turquie", code_tel: "90" },
    { id: "229", code: "TM", name_en: "Turkmenistan", name: "Turkménistan", code_tel: "993" },
    { id: "230", code: "TC", name_en: "Turks and Caicos Islands", name: "Îles Turques-et-Caïques", code_tel: "1+649" },
    { id: "231", code: "TV", name_en: "Tuvalu", name: "Tuvalu", code_tel: "688" },
    { id: "232", code: "UG", name_en: "Uganda", name: "Ouganda", code_tel: "256" },
    { id: "233", code: "UA", name_en: "Ukraine", name: "Ukraine", code_tel: "380" },
    { id: "234", code: "AE", name_en: "United Arab Emirates", name: "Émirats arabes unis", code_tel: "971" },
    { id: "235", code: "GB", name_en: "United Kingdom", name: "Royaume-Uni", code_tel: "44" },
    { id: "236", code: "US", name_en: "United States", name: "États-Unis", code_tel: "1" },
    { id: "237", code: "UM", name_en: "United States Minor Outlying Islands", name: "Îles mineures éloignées des États-Unis", code_tel: "NONE" },
    { id: "238", code: "UY", name_en: "Uruguay", name: "Uruguay", code_tel: "598" },
    { id: "239", code: "UZ", name_en: "Uzbekistan", name: "Ouzbékistan", code_tel: "998" },
    { id: "240", code: "VU", name_en: "Vanuatu", name: "Vanuatu", code_tel: "678" },
    { id: "241", code: "VA", name_en: "Vatican City", name: "Vatican (Cité du)", code_tel: "39" },
    { id: "242", code: "VE", name_en: "Venezuela", name: "Venezuela", code_tel: "58" },
    { id: "243", code: "VN", name_en: "Vietnam", name: "Viêt Nam", code_tel: "84" },
    { id: "244", code: "VG", name_en: "Virgin Islands, British", name: "Îles Vierges britanniques", code_tel: "1+284" },
    { id: "245", code: "VI", name_en: "Virgin Islands, US", name: "Îles Vierges des États-Unis", code_tel: "1+340" },
    { id: "246", code: "WF", name_en: "Wallis and Futuna", name: "Wallis-et-Futuna", code_tel: "681" },
    { id: "247", code: "EH", name_en: "Western Sahara", name: "Sahara occidental", code_tel: "212" },
    { id: "248", code: "YE", name_en: "Yemen", name: "Yémen", code_tel: "967" },
    { id: "249", code: "ZM", name_en: "Zambia", name: "Zambie", code_tel: "260" },
    { id: "250", code: "ZW", name_en: "Zimbabwe", name: "Zimbabwe", code_tel: "263" },
];

export default countries;
