const currencies = [
    { id: "1", code: "USD", name_en: "US Dollar", name_fr: "Dollar américain", code_country: "US" },
    { id: "2", code: "EUR", name_en: "Euro", name_fr: "Euro", code_country: "EU" },
    { id: "3", code: "CDF", name_en: "Congolese Franc", name_fr: "Franc congolais", code_country: "CD" },
    { id: "4", code: "XAF", name_en: "Central African CFA Franc", name_fr: "Franc CFA d'Afrique Centrale", code_country: "CM" },
    { id: "5", code: "CDF", name_en: "West African CFA Franc", name_fr: "Franc CFA d'Afrique de l'Ouest", code_country: "BJ" },
    { id: "6", code: "GBP", name_en: "British Pound", name_fr: "Livre sterling", code_country: "GB" },
    { id: "7", code: "JPY", name_en: "Japanese Yen", name_fr: "Yen japonais", code_country: "JP" },
    { id: "8", code: "CNY", name_en: "Chinese Yuan", name_fr: "Yuan chinois", code_country: "CN" },
    { id: "9", code: "INR", name_en: "Indian Rupee", name_fr: "Roupie indienne", code_country: "IN" },
    { id: "10", code: "RUB", name_en: "Russian Ruble", name_fr: "Rouble russe", code_country: "RU" },
    { id: "11", code: "BRL", name_en: "Brazilian Real", name_fr: "Réal brésilien", code_country: "BR" },
    { id: "12", code: "ZAR", name_en: "South African Rand", name_fr: "Rand sud-africain", code_country: "ZA" },
    { id: "13", code: "NGN", name_en: "Nigerian Naira", name_fr: "Naira nigérian", code_country: "NG" },
    { id: "14", code: "MXN", name_en: "Mexican Peso", name_fr: "Peso mexicain", code_country: "MX" },
    { id: "15", code: "AUD", name_en: "Australian Dollar", name_fr: "Dollar australien", code_country: "AU" },
    { id: "16", code: "CAD", name_en: "Canadian Dollar", name_fr: "Dollar canadien", code_country: "CA" },
    { id: "17", code: "CHF", name_en: "Swiss Franc", name_fr: "Franc suisse", code_country: "CH" },
    { id: "18", code: "KRW", name_en: "South Korean Won", name_fr: "Won sud-coréen", code_country: "KR" },
    { id: "19", code: "TRY", name_en: "Turkish Lira", name_fr: "Livre turque", code_country: "TR" },
    { id: "20", code: "SAR", name_en: "Saudi Riyal", name_fr: "Riyal saoudien", code_country: "SA" },
    { id: "21", code: "EGP", name_en: "Egyptian Pound", name_fr: "Livre égyptienne", code_country: "EG" },
    { id: "22", code: "MAD", name_en: "Moroccan Dirham", name_fr: "Dirham marocain", code_country: "MA" },
    { id: "23", code: "TND", name_en: "Tunisian Dinar", name_fr: "Dinar tunisien", code_country: "TN" },
    { id: "24", code: "DZD", name_en: "Algerian Dinar", name_fr: "Dinar algérien", code_country: "DZ" },
    { id: "25", code: "LYD", name_en: "Libyan Dinar", name_fr: "Dinar libyen", code_country: "LY" },
    { id: "26", code: "GHS", name_en: "Ghanaian Cedi", name_fr: "Cedi ghanéen", code_country: "GH" },
    { id: "27", code: "KES", name_en: "Kenyan Shilling", name_fr: "Shilling kényan", code_country: "KE" },
    { id: "28", code: "TZS", name_en: "Tanzanian Shilling", name_fr: "Shilling tanzanien", code_country: "TZ" },
    { id: "29", code: "ETB", name_en: "Ethiopian Birr", name_fr: "Birr éthiopien", code_country: "ET" },
    { id: "30", code: "UGX", name_en: "Ugandan Shilling", name_fr: "Shilling ougandais", code_country: "UG" },
    { id: "31", code: "BIF", name_en: "Burundian Franc", name_fr: "Franc burundais", code_country: "BI" },
    { id: "32", code: "RWF", name_en: "Rwandan Franc", name_fr: "Franc rwandais", code_country: "RW" },
    { id: "33", code: "AOA", name_en: "Angolan Kwanza", name_fr: "Kwanza angolais", code_country: "AO" },
    { id: "34", code: "ZMW", name_en: "Zambian Kwacha", name_fr: "Kwacha zambien", code_country: "ZM" },
    { id: "35", code: "SLL", name_en: "Sierra Leonean Leone", name_fr: "Leone sierra-léonais", code_country: "SL" },
    { id: "36", code: "LSL", name_en: "Lesotho Loti", name_fr: "Loti lesothan", code_country: "LS" },
    { id: "37", code: "NAD", name_en: "Namibian Dollar", name_fr: "Dollar namibien", code_country: "NA" },
    { id: "38", code: "MZN", name_en: "Mozambican Metical", name_fr: "Metical mozambicain", code_country: "MZ" },
    { id: "39", code: "BWP", name_en: "Botswana Pula", name_fr: "Pula botswanais", code_country: "BW" },
    { id: "40", code: "MUR", name_en: "Mauritian Rupee", name_fr: "Roupie mauricienne", code_country: "MU" },
    { id: "41", code: "SCR", name_en: "Seychellois Rupee", name_fr: "Roupie seychelloise", code_country: "SC" },
    { id: "42", code: "GMD", name_en: "Gambian Dalasi", name_fr: "Dalasi gambien", code_country: "GM" },
    { id: "43", code: "GNF", name_en: "Guinean Franc", name_fr: "Franc guinéen", code_country: "GN" },
    { id: "44", code: "LRD", name_en: "Liberian Dollar", name_fr: "Dollar libérien", code_country: "LR" },
    { id: "45", code: "SHP", name_en: "Saint Helena Pound", name_fr: "Livre de Sainte-Hélène", code_country: "SH" },
    { id: "46", code: "SZL", name_en: "Swazi Lilangeni", name_fr: "Lilangeni swazi", code_country: "SZ" },
    { id: "47", code: "MGA", name_en: "Malagasy Ariary", name_fr: "Ariary malgache", code_country: "MG" },
    { id: "48", code: "ERN", name_en: "Eritrean Nakfa", name_fr: "Nakfa érythréen", code_country: "ER" },
    { id: "49", code: "SSP", name_en: "South Sudanese Pound", name_fr: "Livre sud-soudanaise", code_country: "SS" },
    { id: "50", code: "MRU", name_en: "Mauritanian Ouguiya", name_fr: "Ouguiya mauritanien", code_country: "MR" },
    { id: "51", code: "DJF", name_en: "Djiboutian Franc", name_fr: "Franc djiboutien", code_country: "DJ" },
    { id: "52", code: "SOS", name_en: "Somali Shilling", name_fr: "Shilling somalien", code_country: "SO" },
    { id: "53", code: "VES", name_en: "Venezuelan Bolívar", name_fr: "Bolivar vénézuélien", code_country: "VE" },
    { id: "54", code: "COP", name_en: "Colombian Peso", name_fr: "Peso colombien", code_country: "CO" },
    { id: "55", code: "ARS", name_en: "Argentine Peso", name_fr: "Peso argentin", code_country: "AR" },
    { id: "56", code: "CLP", name_en: "Chilean Peso", name_fr: "Peso chilien", code_country: "CL" },
    { id: "57", code: "PEN", name_en: "Peruvian Sol", name_fr: "Sol péruvien", code_country: "PE" },
    { id: "58", code: "PYG", name_en: "Paraguayan Guarani", name_fr: "Guarani paraguayen", code_country: "PY" },
    { id: "59", code: "BOB", name_en: "Bolivian Boliviano", name_fr: "Boliviano bolivien", code_country: "BO" },
    { id: "60", code: "UYU", name_en: "Uruguayan Peso", name_fr: "Peso uruguayen", code_country: "UY" },
    { id: "61", code: "GTQ", name_en: "Guatemalan Quetzal", name_fr: "Quetzal guatémaltèque", code_country: "GT" },
    { id: "62", code: "HNL", name_en: "Honduran Lempira", name_fr: "Lempira hondurien", code_country: "HN" },
    { id: "63", code: "NIO", name_en: "Nicaraguan Córdoba", name_fr: "Córdoba nicaraguayen", code_country: "NI" },
    { id: "64", code: "CRC", name_en: "Costa Rican Colón", name_fr: "Colón costaricain", code_country: "CR" },
    { id: "65", code: "DOP", name_en: "Dominican Peso", name_fr: "Peso dominicain", code_country: "DO" },
    { id: "66", code: "JMD", name_en: "Jamaican Dollar", name_fr: "Dollar jamaïcain", code_country: "JM" },
    { id: "67", code: "BBD", name_en: "Barbadian Dollar", name_fr: "Dollar barbadien", code_country: "BB" },
    { id: "68", code: "BSD", name_en: "Bahamian Dollar", name_fr: "Dollar bahaméen", code_country: "BS" },
    { id: "69", code: "HTG", name_en: "Haitian Gourde", name_fr: "Gourde haïtienne", code_country: "HT" },
    { id: "70", code: "KYD", name_en: "Cayman Islands Dollar", name_fr: "Dollar des îles Caïmans", code_country: "KY" },
    { id: "71", code: "BZD", name_en: "Belize Dollar", name_fr: "Dollar bélizéen", code_country: "BZ" },
    { id: "72", code: "TTD", name_en: "Trinidad and Tobago Dollar", name_fr: "Dollar de Trinité-et-Tobago", code_country: "TT" },
    { id: "73", code: "FJD", name_en: "Fijian Dollar", name_fr: "Dollar fidjien", code_country: "FJ" },
    { id: "74", code: "PGK", name_en: "Papua New Guinean Kina", name_fr: "Kina papou-néo-guinéen", code_country: "PG" },
    { id: "75", code: "SBD", name_en: "Solomon Islands Dollar", name_fr: "Dollar des îles Salomon", code_country: "SB" },
    { id: "76", code: "TOP", name_en: "Tongan Paʻanga", name_fr: "Paʻanga tongien", code_country: "TO" },
    { id: "77", code: "VUV", name_en: "Vanuatu Vatu", name_fr: "Vatu vanuatais", code_country: "VU" },
    { id: "78", code: "WST", name_en: "Samoan Tala", name_fr: "Tala samoan", code_country: "WS" },
    { id: "79", code: "KID", name_en: "Kiribati Dollar", name_fr: "Dollar kiribatien", code_country: "KI" },
    { id: "80", code: "NZD", name_en: "New Zealand Dollar", name_fr: "Dollar néo-zélandais", code_country: "NZ" },
    { id: "81", code: "TVD", name_en: "Tuvaluan Dollar", name_fr: "Dollar tuvaluan", code_country: "TV" },
    { id: "82", code: "BND", name_en: "Brunei Dollar", name_fr: "Dollar de Brunei", code_country: "BN" },
    { id: "83", code: "SGD", name_en: "Singapore Dollar", name_fr: "Dollar singapourien", code_country: "SG" },
    { id: "84", code: "MYR", name_en: "Malaysian Ringgit", name_fr: "Ringgit malaisien", code_country: "MY" },
    { id: "85", code: "IDR", name_en: "Indonesian Rupiah", name_fr: "Roupie indonésienne", code_country: "ID" },
    { id: "86", code: "VND", name_en: "Vietnamese Dong", name_fr: "Dong vietnamien", code_country: "VN" },
    { id: "87", code: "LAK", name_en: "Lao Kip", name_fr: "Kip laotien", code_country: "LA" },
    { id: "88", code: "KHR", name_en: "Cambodian Riel", name_fr: "Riel cambodgien", code_country: "KH" },
    { id: "89", code: "THB", name_en: "Thai Baht", name_fr: "Baht thaïlandais", code_country: "TH" },
    { id: "90", code: "MMK", name_en: "Burmese Kyat", name_fr: "Kyat birman", code_country: "MM" },
    { id: "91", code: "PHP", name_en: "Philippine Peso", name_fr: "Peso philippin", code_country: "PH" },
    { id: "92", code: "BHD", name_en: "Bahraini Dinar", name_fr: "Dinar bahreïni", code_country: "BH" },
    { id: "93", code: "IQD", name_en: "Iraqi Dinar", name_fr: "Dinar irakien", code_country: "IQ" },
    { id: "94", code: "JOD", name_en: "Jordanian Dinar", name_fr: "Dinar jordanien", code_country: "JO" },
    { id: "95", code: "KWD", name_en: "Kuwaiti Dinar", name_fr: "Dinar koweïtien", code_country: "KW" },
    { id: "96", code: "OMR", name_en: "Omani Rial", name_fr: "Rial omanais", code_country: "OM" },
    { id: "97", code: "QAR", name_en: "Qatari Riyal", name_fr: "Riyal qatari", code_country: "QA" },
    { id: "98", code: "AED", name_en: "United Arab Emirates Dirham", name_fr: "Dirham des Émirats arabes unis", code_country: "AE" },
    { id: "99", code: "IRR", name_en: "Iranian Rial", name_fr: "Rial iranien", code_country: "IR" },
    { id: "100", code: "AFN", name_en: "Afghan Afghani", name_fr: "Afghani afghan", code_country: "AF" },
    { id: "101", code: "PKR", name_en: "Pakistani Rupee", name_fr: "Roupie pakistanaise", code_country: "PK" },
    { id: "102", code: "LKR", name_en: "Sri Lankan Rupee", name_fr: "Roupie srilankaise", code_country: "LK" },
    { id: "103", code: "MVR", name_en: "Maldivian Rufiyaa", name_fr: "Roupie maldivienne", code_country: "MV" },
    { id: "104", code: "NPR", name_en: "Nepalese Rupee", name_fr: "Roupie népalaise", code_country: "NP" },
    { id: "105", code: "BDT", name_en: "Bangladeshi Taka", name_fr: "Taka bangladais", code_country: "BD" },
    { id: "106", code: "KGS", name_en: "Kyrgyzstani Som", name_fr: "Som kirghize", code_country: "KG" },
    { id: "107", code: "TJS", name_en: "Tajikistani Somoni", name_fr: "Somoni tadjik", code_country: "TJ" },
    { id: "108", code: "UZS", name_en: "Uzbekistani Som", name_fr: "Som ouzbek", code_country: "UZ" },
    { id: "109", code: "TMT", name_en: "Turkmenistani Manat", name_fr: "Manat turkmène", code_country: "TM" },
    { id: "110", code: "GEL", name_en: "Georgian Lari", name_fr: "Lari géorgien", code_country: "GE" },
    { id: "111", code: "AMD", name_en: "Armenian Dram", name_fr: "Dram arménien", code_country: "AM" },
    { id: "112", code: "AZN", name_en: "Azerbaijani Manat", name_fr: "Manat azerbaïdjanais", code_country: "AZ" },
    { id: "113", code: "BYN", name_en: "Belarusian Ruble", name_fr: "Rouble biélorusse", code_country: "BY" },
    { id: "114", code: "MDL", name_en: "Moldovan Leu", name_fr: "Leu moldave", code_country: "MD" },
    { id: "115", code: "UAH", name_en: "Ukrainian Hryvnia", name_fr: "Hryvnia ukrainienne", code_country: "UA" },
    { id: "116", code: "PLN", name_en: "Polish Zloty", name_fr: "Zloty polonais", code_country: "PL" },
    { id: "117", code: "CZK", name_en: "Czech Koruna", name_fr: "Couronne tchèque", code_country: "CZ" },
    { id: "118", code: "HUF", name_en: "Hungarian Forint", name_fr: "Forint hongrois", code_country: "HU" },
    { id: "119", code: "RON", name_en: "Romanian Leu", name_fr: "Leu roumain", code_country: "RO" },
    { id: "120", code: "BGN", name_en: "Bulgarian Lev", name_fr: "Lev bulgare", code_country: "BG" },
    { id: "121", code: "RSD", name_en: "Serbian Dinar", name_fr: "Dinar serbe", code_country: "RS" },
    { id: "122", code: "HRK", name_en: "Croatian Kuna", name_fr: "Kuna croate", code_country: "HR" },
    { id: "123", code: "MKD", name_en: "Macedonian Denar", name_fr: "Denar macédonien", code_country: "MK" },
    { id: "124", code: "ALL", name_en: "Albanian Lek", name_fr: "Lek albanais", code_country: "AL" },
    { id: "125", code: "ISK", name_en: "Icelandic Krona", name_fr: "Couronne islandaise", code_country: "IS" },
    { id: "126", code: "NOK", name_en: "Norwegian Krone", name_fr: "Couronne norvégienne", code_country: "NO" },
    { id: "127", code: "SEK", name_en: "Swedish Krona", name_fr: "Couronne suédoise", code_country: "SE" },
    { id: "128", code: "DKK", name_en: "Danish Krone", name_fr: "Couronne danoise", code_country: "DK" },
    { id: "129", code: "FOK", name_en: "Faroese Króna", name_fr: "Couronne féroïenne", code_country: "FO" },
    { id: "130", code: "GIP", name_en: "Gibraltar Pound", name_fr: "Livre de Gibraltar", code_country: "GI" },
    { id: "131", code: "IMP", name_en: "Isle of Man Pound", name_fr: "Livre de l'île de Man", code_country: "IM" },
    { id: "132", code: "JEP", name_en: "Jersey Pound", name_fr: "Livre de Jersey", code_country: "JE" },
    { id: "133", code: "GGY", name_en: "Guernsey Pound", name_fr: "Livre de Guernesey", code_country: "GG" },
    { id: "134", code: "SPL", name_en: "Seborga Luigino", name_fr: "Luigino de Seborga", code_country: "SB" },
    { id: "135", code: "KPW", name_en: "North Korean Won", name_fr: "Won nord-coréen", code_country: "KP" },
    { id: "136", code: "TVD", name_en: "Tuvaluan Dollar", name_fr: "Dollar tuvaluan", code_country: "TV" },
    { id: "137", code: "CUC", name_en: "Cuban Convertible Peso", name_fr: "Peso cubain convertible", code_country: "CU" },
    { id: "138", code: "CUP", name_en: "Cuban Peso", name_fr: "Peso cubain", code_country: "CU" },
    { id: "139", code: "VES", name_en: "Venezuelan Bolívar", name_fr: "Bolivar vénézuélien", code_country: "VE" },
    { id: "140", code: "XCD", name_en: "East Caribbean Dollar", name_fr: "Dollar des Caraïbes orientales", code_country: "AG" },
    { id: "141", code: "SRD", name_en: "Surinamese Dollar", name_fr: "Dollar surinamais", code_country: "SR" },
    { id: "142", code: "ANG", name_en: "Netherlands Antillean Guilder", name_fr: "Florin des Antilles néerlandaises", code_country: "CW" },
    { id: "143", code: "AWG", name_en: "Aruban Florin", name_fr: "Florin arubais", code_country: "AW" },
    { id: "144", code: "MNT", name_en: "Mongolian Tögrög", name_fr: "Tugrik mongol", code_country: "MN" },
    { id: "145", code: "BAM", name_en: "Bosnia and Herzegovina Convertible Mark", name_fr: "Mark convertible bosnien", code_country: "BA" },
    { id: "146", code: "MOP", name_en: "Macanese Pataca", name_fr: "Pataca macanaise", code_country: "MO" },
    { id: "147", code: "TWD", name_en: "New Taiwan Dollar", name_fr: "Nouveau dollar taïwanais", code_country: "TW" },
    { id: "148", code: "KMF", name_en: "Comorian Franc", name_fr: "Franc comorien", code_country: "KM" },
    { id: "149", code: "ZWL", name_en: "Zimbabwean Dollar", name_fr: "Dollar zimbabwéen", code_country: "ZW" },
    { id: "150", code: "FKP", name_en: "Falkland Islands Pound", name_fr: "Livre des îles Falkland", code_country: "FK" },
    { id: "151", code: "SYP", name_en: "Syrian Pound", name_fr: "Livre syrienne", code_country: "SY" },
    { id: "152", code: "YER", name_en: "Yemeni Rial", name_fr: "Rial yéménite", code_country: "YE" },
    { id: "153", code: "SOS", name_en: "Somali Shilling", name_fr: "Shilling somalien", code_country: "SO" },
    { id: "154", code: "DJF", name_en: "Djiboutian Franc", name_fr: "Franc djiboutien", code_country: "DJ" },
    { id: "155", code: "ERN", name_en: "Eritrean Nakfa", name_fr: "Nakfa érythréen", code_country: "ER" },
    { id: "156", code: "AOA", name_en: "Angolan Kwanza", name_fr: "Kwanza angolais", code_country: "AO" },
    { id: "157", code: "SLL", name_en: "Sierra Leonean Leone", name_fr: "Leone sierra-léonais", code_country: "SL" },
    { id: "158", code: "BIF", name_en: "Burundian Franc", name_fr: "Franc burundais", code_country: "BI" },
    { id: "159", code: "LSL", name_en: "Lesotho Loti", name_fr: "Loti lesothan", code_country: "LS" },
    { id: "160", code: "NAD", name_en: "Namibian Dollar", name_fr: "Dollar namibien", code_country: "NA" },
    { id: "161", code: "MGA", name_en: "Malagasy Ariary", name_fr: "Ariary malgache", code_country: "MG" },
    { id: "162", code: "SCR", name_en: "Seychellois Rupee", name_fr: "Roupie seychelloise", code_country: "SC" },
    { id: "163", code: "TZS", name_en: "Tanzanian Shilling", name_fr: "Shilling tanzanien", code_country: "TZ" },
    { id: "164", code: "ZMW", name_en: "Zambian Kwacha", name_fr: "Kwacha zambien", code_country: "ZM" },
    { id: "165", code: "SSP", name_en: "South Sudanese Pound", name_fr: "Livre sud-soudanaise", code_country: "SS" },
    { id: "166", code: "MRU", name_en: "Mauritanian Ouguiya", name_fr: "Ouguiya mauritanien", code_country: "MR" },
    { id: "167", code: "GMD", name_en: "Gambian Dalasi", name_fr: "Dalasi gambien", code_country: "GM" },
    { id: "168", code: "GNF", name_en: "Guinean Franc", name_fr: "Franc guinéen", code_country: "GN" },
    { id: "169", code: "LRD", name_en: "Liberian Dollar", name_fr: "Dollar libérien", code_country: "LR" },
    { id: "170", code: "MWK", name_en: "Malawian Kwacha", name_fr: "Kwacha malawien", code_country: "MW" },
    { id: "171", code: "SZL", name_en: "Swazi Lilangeni", name_fr: "Lilangeni swazi", code_country: "SZ" },
    { id: "172", code: "KPW", name_en: "North Korean Won", name_fr: "Won nord-coréen", code_country: "KP" },
    { id: "173", code: "GEL", name_en: "Georgian Lari", name_fr: "Lari géorgien", code_country: "GE" },
    { id: "174", code: "AMD", name_en: "Armenian Dram", name_fr: "Dram arménien", code_country: "AM" },
    { id: "175", code: "AZN", name_en: "Azerbaijani Manat", name_fr: "Manat azerbaïdjanais", code_country: "AZ" },
    { id: "176", code: "TMT", name_en: "Turkmenistani Manat", name_fr: "Manat turkmène", code_country: "TM" },
    { id: "177", code: "KGS", name_en: "Kyrgyzstani Som", name_fr: "Som kirghize", code_country: "KG" },
    { id: "178", code: "TJS", name_en: "Tajikistani Somoni", name_fr: "Somoni tadjik", code_country: "TJ" },
    { id: "179", code: "UZS", name_en: "Uzbekistani Som", name_fr: "Som ouzbek", code_country: "UZ" },
    { id: "180", code: "BTN", name_en: "Bhutanese Ngultrum", name_fr: "Ngultrum bhoutanais", code_country: "BT" },
    { id: "181", code: "XPF", name_en: "CFP Franc", name_fr: "Franc CFP", code_country: "PF" },
    { id: "182", code: "CUC", name_en: "Cuban Convertible Peso", name_fr: "Peso cubain convertible", code_country: "CU" },
    { id: "183", code: "STN", name_en: "São Tomé and Príncipe Dobra", name_fr: "Dobra de São Tomé-et-Príncipe", code_country: "ST" },
    { id: "184", code: "VES", name_en: "Venezuelan Bolívar", name_fr: "Bolivar vénézuélien", code_country: "VE" },
    { id: "185", code: "SVC", name_en: "Salvadoran Colón", name_fr: "Colón salvadorien", code_country: "SV" },
    { id: "186", code: "YUM", name_en: "Yugoslav Dinar (Old)", name_fr: "Dinar yougoslave (ancien)", code_country: "YU" },
    { id: "187", code: "CHE", name_en: "WIR Euro", name_fr: "WIR Euro", code_country: "CH" },
    { id: "188", code: "CHW", name_en: "WIR Franc", name_fr: "WIR Franc", code_country: "CH" },
    { id: "189", code: "UYI", name_en: "Uruguayan Peso en Unidades Indexadas", name_fr: "Peso uruguayen en unités indexées", code_country: "UY" },
    { id: "190", code: "COU", name_en: "Colombian Unidad de Valor Real", name_fr: "Unité de valeur réelle colombienne", code_country: "CO" },
    { id: "191", code: "MXV", name_en: "Mexican Unidad de Inversión", name_fr: "Unité d'investissement mexicaine", code_country: "MX" },
    { id: "192", code: "XSU", name_en: "Sucre", name_fr: "Sucre", code_country: "SU" },
    { id: "193", code: "XUA", name_en: "ADB Unit of Account", name_fr: "Unité de compte de la BAD", code_country: "AF" },
    { id: "194", code: "AFA", name_en: "Afghan Afghani (old)", name_fr: "Afghani afghan (ancien)", code_country: "AF" },
    { id: "195", code: "TRL", name_en: "Old Turkish Lira", name_fr: "Ancienne Livre turque", code_country: "TR" },
    { id: "196", code: "ZMK", name_en: "Zambian Kwacha (old)", name_fr: "Kwacha zambien (ancien)", code_country: "ZM" },
    { id: "197", code: "MZM", name_en: "Mozambican Metical (old)", name_fr: "Metical mozambicain (ancien)", code_country: "MZ" },
    { id: "198", code: "BYR", name_en: "Belarusian Ruble (old)", name_fr: "Rouble biélorusse (ancien)", code_country: "BY" },
    { id: "199", code: "RUR", name_en: "Russian Ruble (1991-1998)", name_fr: "Rouble russe (1991-1998)", code_country: "RU" },
    { id: "200", code: "LTL", name_en: "Lithuanian Litas", name_fr: "Litas lituanien", code_country: "LT" },
    { id: "201", code: "LVL", name_en: "Latvian Lats", name_fr: "Lats letton", code_country: "LV" },
    { id: "202", code: "EEK", name_en: "Estonian Kroon", name_fr: "Couronne estonienne", code_country: "EE" },
    { id: "203", code: "CYP", name_en: "Cypriot Pound", name_fr: "Livre chypriote", code_country: "CY" },
    { id: "204", code: "MTL", name_en: "Maltese Lira", name_fr: "Lire maltaise", code_country: "MT" },
    { id: "205", code: "BEF", name_en: "Belgian Franc", name_fr: "Franc belge", code_country: "BE" },
    { id: "206", code: "DEM", name_en: "Deutsche Mark", name_fr: "Mark allemand", code_country: "DE" },
    { id: "207", code: "FRF", name_en: "French Franc", name_fr: "Franc français", code_country: "FR" },
    { id: "208", code: "ITL", name_en: "Italian Lira", name_fr: "Lire italienne", code_country: "IT" },
    { id: "209", code: "NLG", name_en: "Dutch Guilder", name_fr: "Florin néerlandais", code_country: "NL" },
    { id: "210", code: "ESP", name_en: "Spanish Peseta", name_fr: "Peseta espagnole", code_country: "ES" },
    { id: "211", code: "PTE", name_en: "Portuguese Escudo", name_fr: "Escudo portugais", code_country: "PT" },
    { id: "212", code: "IEP", name_en: "Irish Pound", name_fr: "Livre irlandaise", code_country: "IE" },
    { id: "213", code: "GRD", name_en: "Greek Drachma", name_fr: "Drachme grecque", code_country: "GR" },
    { id: "214", code: "SKK", name_en: "Slovak Koruna", name_fr: "Couronne slovaque", code_country: "SK" },
    { id: "215", code: "SIT", name_en: "Slovenian Tolar", name_fr: "Tolar slovène", code_country: "SI" },
    { id: "216", code: "LUF", name_en: "Luxembourg Franc", name_fr: "Franc luxembourgeois", code_country: "LU" },
];

export default currencies;
